version: "3.5"

services:
  server:
    build: ./server
    image: flowi-server
    expose:
      - "3001"
    command: node_modules/.bin/nodemon index.js
    volumes:
      - ./server/:/home/node/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://db:27017/flowi
      - SECRET="0riwOMsuoSj9F6iIk9ycN0cl3pg5WnoUW1EwxzpBuzEfNUkTRMNPQ6j4FUjE2wq"
    ports:
      - 3001:3001
    depends_on:
      - db

  client:
    build: ./client
    image: flowi-client
    expose:
      - "3000"
    command: npm start
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: mongo:4.0.10-xenial
    volumes:
      - ./data:/data/db
    logging:
      driver: "none"
