version: '3.5'

services:

  server:
    build: ./server/
    volumes:
      - ./server/:/home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001

  client:
    build: ./client/
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    links:
      - server
    