version: "3.5"

services:
  server:
    build: ./server
    image: flowi-server
    container_name: flowi-server_1
    expose:
      - "3001"
    command: [sh, -c, "/wait && nodemon index.js"]
    volumes:
      - ./server/:/usr/local/app
      - /usr/local/app/node_modules/
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://db:27017/flowi
      - MONGODB_TESTING_URI=mongodb://db:27017/flowi-testing
      - SECRET="0riwOMsuoSj9F6iIk9ycN0cl3pg5WnoUW1EwxzpBuzEfNUkTRMNPQ6j4FUjE2wq"
      - WAIT_HOSTS=db:27017
    ports:
      - 3001:3001
    depends_on:
      - db

  client:
    build: ./client
    image: flowi-client
    container_name: flowi-client_1
    expose:
      - "3000"
    command: npm start
    volumes:
      - ./client/:/usr/local/app
      - /usr/local/app/node_modules/
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: mongo:4.0.10-xenial
    container_name: flowi-db_1
    volumes:
      - flowi_data:/data/db
    logging:
      driver: "none"

volumes:
  flowi_data: