version: '3.5'

services:

  server:
    build: ./server/
    command: node index.js
    volumes:
      - ./server/:/home/node/app
    environment:
      - NODE_ENV=test
      - PORT=3001
      - MONGODB_URI=mongodb://db:27017/flowi-test
    ports:
      - 3001:3001
    depends_on:
      - db

  client:
    build: ./client/
    command: npm start
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=test
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  cypress:
    image: "cypress/included:3.2.0"
    volumes:
      - ./e2e:/e2e
    environment:
      - CYPRESS_baseUrl=http://server:3001/api
    working_dir: /e2e
    depends_on:
      - client