version: "3.5"

services:
  server:
    build: ./server
    image: flowi-server
    expose:
      - "3001"
    environment:
      - PORT=3001
      - WAIT_HOSTS=test-db:27017
      - NODE_ENV=test
      - MONGODB_URI=mongodb://test-db:27017/flowi-test
      - SECRET="0riwOMsuoSj9F6iIk9ycN0cl3pg5WnoUW1EwxzpBuzEfNUkTRMNPQ6j4FUjE2wq"
    command: [sh, -c, "/wait && node index.js"]
    volumes:
      - ./server/:/home/node/app
    depends_on:
      - test-db
    restart: on-failure
    networks:
      - flowi_test

  test-client:
    build: ./client
    image: flowi-client
    expose:
      - "3000"
    environment:
      - NODE_ENV=test
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    command: npm start
    volumes:
      - ./client/:/home/node/app
    depends_on:
      - server
    networks:
      - flowi_test

  test-db:
    image: mongo:4.0.10-xenial
    logging:
      driver: "none"
    networks:
      - flowi_test

  cypress:
    image: "cypress/base:10"
    command: bash -c "npm install -D cypress && node_modules/.bin/cypress run"
    volumes:
      - ./e2e:/e2e
    environment:
      - CYPRESS_baseUrl=http://test-client:3000
      - NO_COLOR=1
    working_dir: /e2e
    depends_on:
      - test-client
      - server
    networks:
      - flowi_test

networks:
  flowi_test:
    name: flowi_test
