version: "3.5"

services:
  unit-server:
    build: ./server
    image: flowi-server
    environment:
      - PORT=3001
      - NODE_ENV=test
      - MONGODB_URI=mongodb://test-db:27017/flowi-test
      - SECRET="0riwOMsuoSj9F6iIk9ycN0cl3pg5WnoUW1EwxzpBuzEfNUkTRMNPQ6j4FUjE2wq"
    command: npm run test
    volumes:
      - ./server/:/home/node/app
    depends_on:
      - test-db
    networks:
      - flowi_test

  test-db:
    image: mongo:4.0.10-xenial
    logging:
      driver: "none"
    networks:
      - flowi_test

networks:
  flowi_test:
    name: flowi_test
