version: "3.5"

services:
  test-server:
    command: node index.js
    build: ./server/
    expose:
      - "3001"
    volumes:
      - ./server/:/home/node/app
    environment:
      - PORT=3001
      - NODE_ENV=test
      - MONGODB_URI=mongodb://test-db:27017/flowi-test
    depends_on:
      - test-db
    networks:
      - flowi_test

  test-client:
    build: ./client/
    expose:
      - "3000"
    command: npm start
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=test
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on:
      - test-server
    networks:
      - flowi_test

  test-db:
    image: mongo:4.0.10-xenial
    networks:
      - flowi_test

  cypress:
    image: "cypress/included:3.2.0"
    volumes:
      - ./e2e:/e2e
    environment:
      - CYPRESS_baseUrl=http://test-client:3000
      - NO_COLOR=1
    working_dir: /e2e
    depends_on:
      - test-client
    networks:
      - flowi_test

  jest-server:
    command: npm run test
    build: ./server/
    expose:
      - "3001"
    volumes:
      - ./server/:/home/node/app
    environment:
      - PORT=3001
      - NODE_ENV=test
      - MONGODB_URI=mongodb://test-db:27017/flowi-test
    depends_on:
      - test-db
    networks:
      - flowi_test

  jest-client:
    build: ./client/
    expose:
      - "3000"
    command: npm test
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=test
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - CI=true
    depends_on:
      - test-server
    networks:
      - flowi_test

  lint-server:
    command: npm run lint
    build: ./server/
    expose:
      - "3001"
    volumes:
      - ./server/:/home/node/app
    environment:
      - PORT=3001
      - NODE_ENV=test
      - MONGODB_URI=mongodb://test-db:27017/flowi-test
    networks:
      - flowi_test

  lint-client:
    build: ./client/
    expose:
      - "3000"
    command: npm run lint
    volumes:
      - ./client/:/home/node/app
    environment:
      - NODE_ENV=test
    networks:
      - flowi_test

networks:
  flowi_test:
    name: flowi_test
