name: Deployment

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install root dependencies
        run: npm ci

      - name: Bring up environment
        run: npm run dev

      - name: Run Cypress tests
        run: npm run cypress:run

  build:
    name: 'Publish to dockerhub'
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: daraku/flowi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}